name: genepi-box
channels:
  - conda-forge
  - bioconda
  - defaults
  - dranew
dependencies:
  - biopython>=1.74
  - minimap2>=2.16
  - python>=3.9
  - pip
  - snakemake-minimal
  - gofasta
  - usher>=0.3.2
  - fastqc
  - trimmomatic
  - samtools=1.10
  - hisat2
  - bedtools
  - seqtk=1.3
  - bcftools=1.10
  - varscan
  - picard
  - mafft
  - nextstrain-cli
  - augur
  - auspice
  - nextalign
  - snakemake
  - nextclade
  - git
  - zip
  - php
  - pip:
    - git+https://github.com/cov-lineages/pangoLEARN.git
    - git+https://github.com/cov-lineages/scorpio.git
    - git+https://github.com/cov-lineages/constellations.git
    - git+https://github.com/cov-lineages/pango-designation.git
    - git+https://github.com/cov-lineages/pangolin-data.git
    - epiweeks
