name: cli2_env
channels:
  - conda-forge
  - bioconda
  - pypi
  - nodefaults

dependencies:
  - python==3.9
  - pip==21.2.4
  - requests==2.26.0
  - pandas==1.3.1
  - pip:
    - '-e .' # developer mode install of cli2